image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
  - sudo apt-get -qq update && apt-get -qq install -y python
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y python python-virtualenv python-pip
  - virtualenv venv
  - . venv/bin/activate
  - python3 -V
  - pip3 -V
  - pip3 install mypy pytest

test:
  script:
  - pipenv run mypy --ignore-missing-imports .
  - pipenv run pytest
