image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
  - python3 -V # Print out python version for debugging
  - pip3 install pipenv
  - pipenv install --dev

test:
  script:
  - pipenv run pytest
