variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv

stages:
  - info
  - build
  - test


info:
  stage: info
  script:
    - python3 -V
    - pip3 -V
    - sudo docker info

build:
  stage: build
  before_script:
    - python3 -m pip install pipenv
    - python3 -m pipenv lock -r > req.txt
  script:
    - sudo docker build -f Dockerfile.test --force-rm -t pytest .

test:
  stage: test
  script:
    - sudo docker run --rm pytest:latest
