image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
  - sudo docker info

build_image:
  script:
    sudo docker build --force-rm -t pytest .

test:
  script:
    - sudo docker run --rm pytest:latest
