stages:
  - info
  - build
  - test


info:
  stage: info
  script:
    - sudo docker info

build:
  stage: build
  script:
    - sudo docker build -f Dockerfile.test --force-rm -t pytest .

test:
  stage: test
  script:
    - sudo docker run --rm pytest:latest
