FROM python:3.7

WORKDIR /app
COPY Pipfile* ./

RUN apt-get update && python -m pip install pipenv \
    && pipenv install --dev && apt-get clean

COPY . .
ENTRYPOINT ["pytest"]
CMD ["--disable-pytest-warnings", "--random-order", "-v", "tests/"]
